version: 0.2

phases:
  build:
    commands:
      - echo Starting Build phase
      - mvn clean package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/springApp.jar
  discard-paths: yes